on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: nhartland/love-build@master
        id: love-build
        with:
          app_name: "Calculate to jump!"
          love_version: "11.4"
      - uses: actions/upload-artifact@v1
        with:
          name: ctj-macos
          path: ${{ steps.love-build.outputs.macos-filename }}
      - uses: actions/upload-artifact@v1
        with:
          name: ctj-win32
          path: ${{ steps.love-build.outputs.win32-filename }}
      - uses: actions/upload-artifact@v1
        with:
          name: ctj-win64
          path: ${{ steps.love-build.outputs.win64-filename }}
      - uses: actions/upload-artifact@v1
        with:
          name: ctj-love
          path: ${{ steps.love-build.outputs.love-filename }}